apiVersion: v2
name: rttys
appVersion: "1.0"
description: A Helm chart for Kubernetes
version: 0.1.0
dependencies:
- name: mysql
  repository: https://charts.bitnami.com/bitnami
  version: 8.6.2
  condition: mysql.enabled
