{{- $root := . -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rttys.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "rttys.name" . }}
    helm.sh/chart: {{ include "rttys.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "rttys.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      {{- with .Values.services.rttys.labels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "rttys.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- with .Values.services.rttys.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if .Values.podAnnotations }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:

      initContainers:

        {{- if .Values.mysql.enabled }}
        - name: wait-db
          image: "{{ .Values.images.dockerize.repository }}:{{ .Values.images.dockerize.tag }}"
          imagePullPolicy: {{ .Values.images.dockerize.pullPolicy }}
          command:
            - dockerize
            - -wait
            - tcp://{{ .Release.Name }}-mysql:3306
            - -timeout
            - 60s
        {{- end }}

      containers:

        - name: rttys
          image: "{{ .Values.images.rttys.repository }}:{{ .Values.images.rttys.tag }}"
          imagePullPolicy: {{ .Values.images.rttys.pullPolicy }}

          ports:
          {{- range $port, $portValue := .Values.services.rttys.ports }}
            - name: {{ $port }}
              containerPort: {{ $portValue.targetPort }}
              protocol: {{ $portValue.protocol }}
          {{- end }}

          volumeMounts:
          {{- range .Values.volumes.rttys }}
          - name: {{ .name }}
            mountPath: {{ .mountPath }}
            {{- if .subPath }}
            subPath: {{ .subPath }}
            {{- end }}
          {{- end }}

          {{- if .Values.checks.rttys.liveness }}
          livenessProbe:
            {{- toYaml .Values.checks.rttys.liveness | nindent 12 }}
          {{- end }}
          {{- if .Values.checks.rttys.readiness }}
          readinessProbe:
            {{- toYaml .Values.checks.rttys.readiness | nindent 12 }}
          {{- end }}

          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}


      imagePullSecrets:
      {{- range $image, $imageValue := .Values.images }}
        {{- if $imageValue.regcred }}
      - name: {{ include "rttys.fullname" $root }}-{{ $image }}-regcred
        {{- end }}
      {{- end }}

      volumes:
      {{- range $container, $containerVolumes := .Values.volumes }}
      {{- range $containerVolumes }}
      - name: {{ .name }}
        {{- tpl .volumeDefinition $root | nindent 8 }}
      {{- end }}
      {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
