---
apiVersion: v1
metadata:
  labels:
    app.kuberentes.io/name: {{ include "rttys.name" . }}
    helm.sh/chart: {{ include "rttys.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "rttys.fullname" . }}-config
kind: Secret
type: Opaque
data:
  rttys.conf: {{ include "rttys.config" . | b64enc | quote }}
